name: DarkwebScan
description: A security awareness app that lets you discover if your email has been conpromised.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.5.1
  connectivity: ^2.0.2
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  dio: ^3.0.10
  flutter_bloc: ^6.1.1
  flutter_svg: ^0.19.1
  freezed_annotation: ^0.12.0
  google_fonts: ^1.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  hydrated_bloc: ^6.1.0
  kiwi: ^2.1.1
  lazy_load_scrollview: ^1.2.0
  mockito: ^4.1.3
  path_provider: 1.6.27

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6
  freezed: ^0.12.3
  hive_generator: ^0.8.2
  json_serializable: ^3.5.0
  kiwi_generator: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/svg/launcher_icons/
    - assets/png/launcher_icons/
    - assets/png/
  # flutter packages pub run build_runner build --delete-conflicting-outputs
